Documentation subpackage
eProsima/AML-IP pull request #18
Opened 2022-04-01 07:47 UTC by jparisu

_Bracnh over #17_ 

Add Documentation subpackage with empty documentation

2022-04-04 13:21 UTC, juanlofer-eprosima requested changes

2022-04-04 13:21 UTC, juanlofer-eprosima commented on amlip_docs/CMakeLists.txt
> +# Copyright 2021 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```suggestion
# Copyright 2022 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```

2022-04-04 13:21 UTC, juanlofer-eprosima commented on amlip_docs/cmake/packaging/Config.cmake.in
> +endif()
Is this actually required?

2022-04-04 13:21 UTC, juanlofer-eprosima commented on amlip_docs/cmake/test/cmake_test_utils.cmake
> +# Return a list of all hpp files required by ddsrouter library
change

2022-04-05 06:50 UTC, jparisu commented on amlip_docs/cmake/packaging/Config.cmake.in
> +endif()
This file has been removed

2022-04-05 06:51 UTC, jparisu commented on amlip_docs/cmake/test/cmake_test_utils.cmake
> +# Return a list of all cpp and hpp files required by ddsrouter library
_This file has been removed_

2022-04-05 06:51 UTC, jparisu commented on amlip_docs/cmake/test/cmake_test_utils.cmake
> +# Return a list of all hpp files required by ddsrouter library
_This file has been removed_

2022-04-05 06:54 UTC, jparisu commented
This PR requires the PR https://github.com/eProsima/DDS-Router/pull/180 to be merged in DDS Router main.

2022-04-05 12:15 UTC, juanlofer-eprosima approved these changes
LGTM

2022-04-05 12:16 UTC, merged