Participant Implementation
eProsima/AML-IP pull request #25
Opened 2022-04-07 14:38 UTC by jparisu

2022-04-08 08:24 UTC, juanlofer-eprosima requested changes

2022-04-08 08:24 UTC, juanlofer-eprosima commented on amlip_cpp/src/cpp/dds/Participant.cpp
> +#include <assert.h>
```suggestion
```

2022-04-08 08:24 UTC, juanlofer-eprosima commented on amlip_cpp/src/cpp/types/AmlipIdDataType.hpp
> +    std::array<uint8_t, NAME_SIZE> name_
```suggestion
    std::array<uint8_t, NAME_SIZE> name_;
```

2022-04-21 07:47 UTC, jparisu commented
Merged within PR #28

2022-04-21 07:47 UTC, closed without merging