Multiservice Implementation
eProsima/AML-IP pull request #36
Opened 2022-04-20 12:23 UTC by jparisu

2022-05-04 08:55 UTC, juanlofer-eprosima requested changes

2022-05-20 11:56 UTC, juanlofer-eprosima requested changes

2022-05-20 11:56 UTC, juanlofer-eprosima commented on amlip_cpp/src/cpp/dds/multiservice/MultiServiceServer.hpp
> +    std::atomic<types::TaskId> last_task_id_used_;
```suggestion
```

2022-05-20 11:56 UTC, juanlofer-eprosima commented on amlip_cpp/src/cpp/dds/multiservice/impl/MultiServiceClient.ipp
> +        if (reference.task_id() == this_task_id ||
```suggestion
        if (reference.task_id() == this_task_id &&
```

2022-05-20 11:56 UTC, juanlofer-eprosima commented on amlip_cpp/src/cpp/dds/multiservice/impl/MultiServiceClient.ipp
> +        if (ms_solution.task_id() == this_task_id ||
```suggestion
        if (ms_solution.task_id() == this_task_id &&
```

2022-05-20 11:56 UTC, juanlofer-eprosima commented on amlip_cpp/src/cpp/dds/multiservice/impl/MultiServiceServer.ipp
> +        "Server " << own_id_ << " processing task: " << task_target.server_id() <<
```suggestion
        "Server " << own_id_ << " processing task: " << task_target.task_id() <<
```

2022-05-20 11:56 UTC, juanlofer-eprosima commented on amlip_cpp/test/unittest/dds/entitiesCreationTest.cpp
> +    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
What's this for?

2022-05-20 11:56 UTC, juanlofer-eprosima commented on amlip_cpp/test/manual/dds/msclient.cpp
> +// Copyright 2021 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```suggestion
// Copyright 2022 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```

2022-05-20 11:56 UTC, juanlofer-eprosima commented on amlip_cpp/test/manual/dds/msserver.cpp
> +// Copyright 2021 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```suggestion
// Copyright 2022 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```

2022-05-20 11:56 UTC, juanlofer-eprosima commented on amlip_cpp/test/blackbox/communication/directMessageTest.cpp
> +    Participant source_participant(client_id);
```suggestion
    Participant client_participant(client_id);
```

2022-05-20 11:56 UTC, juanlofer-eprosima commented on amlip_cpp/test/blackbox/communication/directMessageTest.cpp
> +    Participant source_participant(client_id);
Apply changes everywhere else.

2022-05-20 11:56 UTC, juanlofer-eprosima commented on amlip_cpp/test/blackbox/communication/multiserviceTest.cpp
> + * Communicate a MS Client and a MS Server from differenct participants
```suggestion
 * Communicate a MS Client and a MS Server from different participants
```

2022-10-06 09:45 UTC, jparisu commented on amlip_cpp/src/cpp/types/impl/MsDataType.ipp
> +
Why so?

2022-10-06 09:47 UTC, jparisu commented on amlip_cpp/src/cpp/types/impl/MsDataType.ipp
> +    scdr << data_;
I think I did this because something bad happens if not, but lets see

2022-10-06 09:49 UTC, jparisu commented on amlip_cpp/src/cpp/types/impl/MsDataType.ipp
> +    return current_alignment;
if no key, it returns the arg

2022-10-06 13:05 UTC, juanlofer-eprosima commented on amlip_cpp/src/cpp/types/impl/MsDataType.ipp
> +    scdr << data_;
MsReferenceDataType

2022-10-06 13:53 UTC, juanlofer-eprosima approved these changes
LGTM

2022-10-06 14:24 UTC, merged