Main and Computational Node Implementation
eProsima/AML-IP pull request #42
Opened 2022-04-28 12:36 UTC by jparisu

2022-05-23 14:13 UTC, juanlofer-eprosima requested changes

2022-10-11 09:54 UTC, jparisu commented on amlip_cpp/src/cpp/dds/multiservice/impl/MultiServiceServer.ipp
> +        else
This can never happen as the previous loop only exists if both conditions are met.
But I agree with it and I add it.

2022-10-11 09:56 UTC, jparisu commented on amlip_cpp/src/cpp/node/ComputationalNode.hpp
> +class ComputationalNode : public ParentNode
It did not sound correct for me. Computing is not an adjective but a state. 
@rsanchez15 opinion?

2022-10-11 09:57 UTC, jparisu commented on amlip_cpp/src/cpp/node/ComputationalNode.hpp
> +class ComputationalNode : public ParentNode
I would actually change the Main node as well, but this is probably not in our hand

2022-10-13 05:39 UTC, juanlofer-eprosima commented on amlip_cpp/src/cpp/dds/multiservice/impl/MultiServiceServer.ipp
> +        else
Little typo

2022-10-13 05:40 UTC, juanlofer-eprosima commented on amlip_cpp/src/cpp/node/ComputationalNode.hpp
> +class ComputationalNode : public ParentNode
@rsanchez15 ?

2022-10-13 07:46 UTC, juanlofer-eprosima approved these changes
LGTM

2022-10-13 07:47 UTC, merged