public amlip_cpp API [
eProsima/AML-IP pull request #43
Opened 2022-05-11 14:45 UTC by jparisu

2022-11-08 13:54 UTC, irenebm commented on amlip_cpp/include/amlip_cpp/types/id/AmlipIdDataType.hpp
```suggestion
#include <iostream>

```

2022-11-10 13:35 UTC, juanlofer-eprosima requested changes
Uncrustify

2022-11-10 13:35 UTC, juanlofer-eprosima commented on amlip_cpp/include/amlip_cpp/node/StatusNode.hpp
> +     * @pre There could only be called once per instance before calling \c stop_processing
```suggestion
     * @pre Should only be called once per instance before calling \c stop_processing
```

2022-11-10 13:35 UTC, juanlofer-eprosima commented on amlip_cpp/src/cpp/types/id/idl/id.idl
> +struct AmlipId
```suggestion
struct AmlipIdDataType
```

2022-11-11 08:31 UTC, merged