Model Manager Node
eProsima/AML-IP pull request #62
Opened 2022-12-05 12:49 UTC by jparisu

2023-03-21 07:46 UTC, juanlofer-eprosima requested changes

2023-03-21 07:46 UTC, juanlofer-eprosima commented on amlip_cpp/include/amlip_cpp/types/GenericDataType.hpp
> +        const GenericDataType& obj);
Add `%ignore eprosima::amlip::types::operator <<(std::ostream &,const GenericDataType&);` to `GenericDataType.i`.

2023-04-26 06:24 UTC, jparisu reviewed
Changes requested for @irenebm

2023-04-26 06:24 UTC, jparisu commented on amlip_cpp/include/amlip_cpp/node/ParentNode.hpp
> +#include <fastdds/dds/domain/qos/DomainParticipantQos.hpp>
This would be better to have it as a forward declaration, so no fastdds includes are done from these headers

2023-04-26 06:24 UTC, jparisu commented on amlip_cpp/src/cpp/dds/network_utils/dds_qos.hpp
> +        const char* name = DEFAULT_PARTICIPANT_NAME);
NIT: Should we change default name for this?

2023-04-26 06:24 UTC, jparisu commented on amlip_cpp/src/cpp/node/ParentNode.cpp
> +    : participant_(std::make_unique<dds::Participant>(name, dds::utils::default_domain_participant_qos(name), domain_id))
This constructor must call the other with the defaulted argument.
This way, the constructor logic is stored in only one function
`    : ParentNode(name, node_kind, initial_state, domain_id, dds::utils::default_domain_participant_qos(name))`

2023-04-26 06:24 UTC, jparisu commented on amlip_cpp/test/blackbox/communication/collaborative_learning/CMakeLists.txt
> +# Copyright 2023 Proyectos y Sistemas de Mantenimiento SL (eProsima).
NIT: be careful with this. The copyright of each file should be the year of creation

2023-04-26 06:24 UTC, jparisu commented on amlip_cpp/test/unittest/node/statusNodeTest.cpp
> -
Why removing this? I understand it is not needed anymore, but it is not wrong either

2023-04-26 06:24 UTC, jparisu commented on amlip_cpp/test/unittest/node/statusNodeTest.cpp
> -        if (data.id() == parent_id)
I'd left the test as it was. If in the future we decide that we want status nodes to receive their own data, this have to change again

2023-04-28 06:03 UTC, jparisu reviewed
LGTM

2023-04-28 06:07 UTC, irenebm approved these changes
LGTM

2023-04-28 06:15 UTC, juanlofer-eprosima approved these changes

2023-04-28 06:15 UTC, merged