Documentation
eProsima/AML-IP pull request #64
Opened 2022-12-12 16:01 UTC by jparisu

After PR: #58

2022-12-14 10:04 UTC, rsanchez15 commented on amlip_docs/rst/user_manual/nodes/nodes.rst
> +In this last case, the Nodes are programming *Classes* that can be instantiated and customize regarding the
```suggestion
In this last case, the Nodes are programming *Objects* that can be instantiated and customize regarding the
```

2022-12-14 10:06 UTC, rsanchez15 commented on amlip_docs/rst/user_manual/nodes/nodes.rst
> +In principle, there is are no restrictions in the number of nodes of the same kind running in the same network.
```suggestion
There are no restrictions in the number of nodes of the same kind running in the same network.
```

2022-12-14 10:08 UTC, rsanchez15 commented on amlip_docs/rst/user_manual/nodes/status.rst
> +This node is executed with a *function* associated that will be executed with each message received.
```suggestion
This node runs a *function* that will be executed with each message received.
```

2022-12-14 10:09 UTC, rsanchez15 commented on amlip_docs/rst/user_manual/nodes/status.rst
> +By destroying the node every internal entity is correctly destroyed (if running, it stops automatically).
I don't get the last part _if running, it stops automatically_

2022-12-14 10:11 UTC, rsanchez15 commented on amlip_docs/rst/user_manual/scenarios/scenarios.rst
> +for an :term:`AML` network.
```suggestion
The |amlip| framework is divided in different **scenarios** or **use cases** that allow it to exploit all the capabilities :term:`AML`.
```

2022-12-14 10:13 UTC, rsanchez15 commented on amlip_docs/rst/user_manual/scenarios/scenarios.rst
> +one to each other in order to create a complex network.
```suggestion
These scenarios work independently of each other and make sense separately, but can be seamlessly integrated with each other to create a more complex network.
```

2022-12-14 10:13 UTC, rsanchez15 commented on amlip_docs/rst/user_manual/scenarios/scenarios.rst
> +In order to know more about the *Node* concept and their kinds, refer to :ref:`user_manual_nodes` section.
```suggestion
In order to know more about the *Node* concept and their kinds, please refer to :ref:`user_manual_nodes` section.
```

2022-12-14 10:17 UTC, rsanchez15 commented on amlip_docs/rst/developer_manual/installation/sources/linux/linux.rst
> +If it already exists in the system an installation of these libraries there is no need to build them again,
```suggestion
If they are already available in the system there is no need to build them again,
```

2022-12-15 06:39 UTC, jparisu commented on amlip_docs/rst/formalia/titlepage.rst
> +human-centric machine learning systems.
Otherwise docs tests fail.
And I do not see why not. I think is clearer this way

2022-12-15 06:44 UTC, jparisu commented on amlip_docs/rst/getting_started/project_overview.rst
> +|amlip| is a complex framework that consist in different parts.
`composed` I think. Please, check it

2022-12-15 06:48 UTC, jparisu commented on amlip_docs/rst/notes/notes.rst
> +##############
A good IT guy always starts counting in 0
Aren't you a good IT guy? :new_moon_with_face:

2022-12-15 06:50 UTC, jparisu commented on amlip_docs/rst/user_manual/dds/dds.rst
> +So an |amlip| topic named , :code:`some_topic` would actually be named :code:`amlip::some_topic` in the underneath
it is in next line

2022-12-15 06:52 UTC, jparisu commented on amlip_docs/rst/user_manual/dds/dds.rst
> +a task in a network.
This is not only reserved for Main and Computings. It could also work to distribute an inference task

2022-12-15 06:57 UTC, jparisu commented on amlip_docs/rst/user_manual/nodes/nodes.rst
> +The kind of the nodes follows the :term:`OOP` ideas, where every Node Kind represents a *class* and can
I think the correct word here is *class*

2022-12-15 06:58 UTC, jparisu commented on amlip_docs/rst/user_manual/nodes/nodes.rst
> +inherit from other Node *classes* (e.g. every Node Kind inherits from :code:`ParentNode`);
same, I think class is better

2022-12-19 13:15 UTC, juanlofer-eprosima requested changes

2022-12-19 13:24 UTC, juanlofer-eprosima commented on amlip_docs/rst/getting_started/project_overview.rst
> +It consist in different application tools that run independently and out-of-the-box.
Maybe merge both sentences: 'composed of different parts/tools/applications that run independently and out-of-the-box.'

2022-12-19 13:31 UTC, juanlofer-eprosima commented on amlip_docs/rst/user_manual/nodes/nodes.rst
> +The kind of the nodes follows the :term:`OOP` ideas, where every Node Kind represents a *class* and can
Agree.

2022-12-19 13:33 UTC, jparisu commented on amlip_docs/rst/formalia/titlepage.rst
> +human-centric machine learning systems.
Finally we eliminate max length

2022-12-19 13:41 UTC, jparisu commented on amlip_docs/rst/appendixes/glossary.rst
> +        **Operative System**
My life is a lie

2022-12-19 13:42 UTC, jparisu commented on amlip_docs/rst/developer_manual/installation/configuration/cmake_options.rst
> +    *   - :class:`BUILD_MANUAL_TESTS`
This CMake option is a temporal necessity because of windows. I would not lose time on it for the moment.

2022-12-19 13:47 UTC, jparisu commented on amlip_docs/rst/developer_manual/installation/sources/linux/linux_colcon.rst
> +    *e.g. the |amlip| C++ library is completely built using :code:`--packages-up-to amlip_cpp`*
because they are in kursive. Good catch

2022-12-19 13:50 UTC, jparisu commented on amlip_docs/rst/developer_manual/installation/configuration/cmake_options.rst
> +    *   - :class:`BUILD_DOCS_TESTS`
add clarification at header

2022-12-19 14:18 UTC, jparisu commented on amlip_docs/rst/getting_started/project_overview.rst
> +.. figure:: /rst/figures/aml_overview.png
No idea why

2022-12-19 14:28 UTC, jparisu commented on amlip_docs/conf.py
>  try:
I think download_css is the same

2022-12-19 14:32 UTC, juanlofer-eprosima commented on amlip_docs/conf.py
>  try:
Sorry, I meant `select_css` : https://github.com/eProsima/vulcanexus/blob/7b4017432fa6322a65d724bf961f3c67441b5fe2/docs/conf.py#L71

2022-12-19 14:49 UTC, juanlofer-eprosima commented on amlip_docs/rst/developer_manual/installation/configuration/cmake_options.rst
> +    *   - :class:`BUILD_MANUAL_TESTS`
I agree it is not worth modifying dev_utils for this, but maybe the second point can be easily fixed in a CMakeLists from this repo.

2022-12-19 14:51 UTC, juanlofer-eprosima commented on amlip_docs/rst/developer_manual/installation/configuration/cmake_options.rst
> +    *   - :class:`BUILD_MANUAL_TESTS`
Clarification added in cmake_options, resolving...

2022-12-19 14:53 UTC, juanlofer-eprosima commented on amlip_docs/rst/developer_manual/installation/sources/windows/windows.rst
> +    `<https://bugs.python.org/issue46276>`_.
Change everywhere else

2022-12-19 14:54 UTC, juanlofer-eprosima commented on amlip_docs/rst/developer_manual/installation/sources/linux/linux.rst
> +**colcon_ version is advice for non advance users as it is easier and neater.**
Change also in Windows.

2022-12-19 14:55 UTC, juanlofer-eprosima commented on amlip_docs/rst/developer_manual/installation/sources/linux/linux.rst
> +    colcon <linux_colcon>
Change in Windows

2022-12-19 15:01 UTC, juanlofer-eprosima commented on amlip_docs/rst/developer_manual/installation/sources/linux/linux_colcon.rst
> +Installation
I think the introduction is too similar to the previous paragraph. Maybe say instead: 'Follow the instructions below to build |eamlip|, after making sure all required dependencies are installed in your system' (with a link to the appropriate subsection)

2022-12-19 15:09 UTC, juanlofer-eprosima commented on amlip_docs/rst/developer_manual/installation/configuration/cmake_options.rst
> +    *   - :class:`BUILD_DOCS_TESTS`
TODO in the future

2022-12-19 15:14 UTC, juanlofer-eprosima commented on amlip_docs/rst/developer_manual/installation/sources/linux/linux_cmake.rst
> +        cmake --build . --target install
Please test it works.

2022-12-19 15:16 UTC, juanlofer-eprosima commented on amlip_docs/rst/getting_started/project_overview.rst
> +.. figure:: /rst/figures/aml_overview.png
Me neither. The preview in Github of the added raw png also shows the line, but I cannot see it when I download it.

2022-12-19 15:21 UTC, juanlofer-eprosima commented on amlip_docs/rst/user_manual/scenarios/workload_distribution.rst
> +Internally, *Jobs* sent from a *Main Node* to a *Computing Node* are treated as bytes array of arbitrary size.
Plural

2022-12-20 07:23 UTC, jparisu commented on amlip_docs/rst/developer_manual/installation/sources/linux/linux_cmake.rst
> +        cmake --build . --target install
Apañao

2022-12-20 08:09 UTC, juanlofer-eprosima approved these changes
LGTM

2022-12-20 08:18 UTC, rsanchez15 approved these changes

2022-12-20 08:22 UTC, merged